//
//  Datas.swift
//  Exercise
//
//  Created by Nguyễn Hoàng on 17/04/2022.
//

import Foundation


let employees: [Employee] = [
    .init(id: "1",
          name: "Alek Hoppe",
          createAt: "2020-07-14T23:50:30.367Z",
          avatar: "undefined - Imgur",
          address: "5481 Alba Lane",
          isMale: true,
          status: "74",
          dayWorking: 3),
    .init(id: "2",
          name: "Ms. Justen O'Hara",
          createAt: "2020-07-14T23:15:09.243Z",
          avatar: "undefined - Imgur (1)",
          address: "002 Dalton Point",
          isMale: false,
          status: "57",
          dayWorking: 20),
    .init(id: "3",
          name: "Elenor Luettgen",
          createAt: "2020-07-15T00:18:55.149Z",
          avatar: "undefined - Imgur (2)",
          address: "7905 Bradtke Passage",
          isMale: false,
          status: "79",
          dayWorking: 3),
    .init(id: "4",
          name: "Mr. Eleanora Miller",
          createAt: "2020-07-14T21:48:22.462Z",
          avatar: "undefined - Imgur (3)",
          address: "125 Cristobal Prairie",
          isMale: true,
          status: "32",
          dayWorking: 200),
    .init(id: "5",
          name: "Davonte Torphy",
          createAt: "2020-07-14T17:12:48.332Z",
          avatar: "undefined - Imgur (4)",
          address: "4036 Lenna Fla",
          isMale: true,
          status: "31",
          dayWorking: 300),
    .init(id: "6",
          name: "Breana Johnson",
          createAt: "2020-07-15T05:56:15.304Z",
          avatar: "undefined - Imgur (5)",
          address: "8829 Baumbach Alley",
          isMale: false,
          status: "43",
          dayWorking: 400),
    .init(id: "7",
          name: "Miss Randy Miller",
          createAt: "2020-07-14T12:01:01.711Z",
          avatar: "undefined - Imgur (6)",
          address: "",
          isMale: false,
          status: "58",
          dayWorking: 111),
    .init(id: "8",
          name: "Mr. Amely Bogisich",
          createAt: "2020-07-15T07:47:01.863Z",
          avatar: "undefined - Imgur (7)",
          address: "477 Dach Land",
          isMale: true,
          status: "53",
          dayWorking: 26),
    .init(id: "9",
          name: "Kadin Kulas Sr.",
          createAt: "2020-07-15T07:59:34.634Z",
          avatar: "undefined - Imgur (8)",
          address: "25025 Adams Track",
          isMale: true,
          status: "58",
          dayWorking: 3),
    .init(id: "10",
          name: "Ashleigh Corkery",
          createAt: "",
          avatar: "undefined - Imgur (9)",
          address: "24847 Gleason Meadows",
          isMale: false,
          status: "45",
          dayWorking: 120),
    .init(id: "11",
          name: "Norberto Reilly",
          createAt: "2020-07-14T14:35:04.436Z",
          avatar: "undefined - Imgur (10)",
          address: "663 Ceasar Vista",
          isMale: true,
          status: "93",
          dayWorking: 98),
    .init(id: "12",
          name: "Lydia Hayes",
          createAt: "2020-07-14T18:41:16.463Z",
          avatar: "undefined - Imgur (11)",
          address: "166 Amani Cliffs",
          isMale: false,
          status: "82",
          dayWorking: 110),
    .init(id: "13",
          name: "Kareem Harber",
          createAt: "2020-07-14T17:15:41.192Z",
          avatar: "undefined - Imgur (12)",
          address: "83768 Robyn View",
          isMale: false,
          status: "41",
          dayWorking: 8),
    .init(id: "14",
          name: "Freda Kilback",
          createAt: "2020-07-14T16:54:34.223Z",
          avatar: "undefined - Imgur (13)",
          address: "4334 Feil Loaf",
          isMale: false,
          status: "35",
          dayWorking: 500)
]
